### ISSUE TITLE
Issues with Tokens

### ISSUE THREAD

**Issue by solderq35** [TalkToBeavs/TalkToBeavs#39]
The bad news is that we have serious issue with Tokens, if you go to the production site right now (https://talktobeavs.onrender.com/) and log in, you **cannot** create new posts. 

![image](https://github.com/Nyumat/TalkToBeavs/assets/82061589/1e0dc136-6a6d-43a6-9df4-77d33e9062b9)

Although I did not rigorously test this, creating / editing / deleting posts (for starters) are broken, even with the correct env file locally (granted I am able to log in), and also it's broken on production.

More Info: https://github.com/Nyumat/TalkToBeavs/pull/38

**Comment by Nyumat** [comment]
Closed -- #41 is merged.

**Comment by solderq35** [comment]
Might have to look into this, Feed is just gone on prod right now (https://talktobeavs.onrender.com/feed).

get_posts API call shows `{"message":"No posts yet"}`

![image](https://github.com/Nyumat/TalkToBeavs/assets/82061589/5b799bfe-5204-45f9-94c1-0629a36d8228)

**Comment by Nyumat** [comment]
Oop, I forgot to alter the FEED_ID, I'll fix it and close

#42
