### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by solderq35** [TalkToBeavs/TalkToBeavs#40]
If this is supposed to be open source project, there are some things not clear to new devs, we should clarify this somewhere not just in a Github PR comment (https://github.com/Nyumat/TalkToBeavs/pull/32#issuecomment-1530016186).

Also I'm not sure how to handle outside contributors who should not (for security reasons) access our backend and database credentials.

Either tell them to use our production API and focus on frontend issues only.

Or teach them how to set up their own backend and database (e.g. on MongoDB free plan) for testing purposes.

**Comment by Nyumat** [comment]
> there are some things not clear to new devs

Can you expand more on what needs to be clarified?

> Also I'm not sure how to handle outside contributors who should not (for security reasons) access our backend and database credentials.

What are you asking, exactly? Our current security measures work against this. 
(JWT, rate limiting, no cors, no x-powered-by, enforcing environment variables)

> Either tell them to use our production API and focus on frontend issues only.

If 'them' is the users who should not access our backend and database credentials, sharing our database credentials can pose a significant security risk and grant unnecessary access to sensitive OSU student data. Focusing on frontend issues would limit a series of developers wanting to contribute to the backend.

> How will developers contribute to the backend or frontend

Three options:
- Give developers our backend credentials
  -  Will go wrong for multiple obvious reasons. Even if we do decide to go about it this way, we'll need to only provide keys to proven contributors. 
- Create a dev. environment for contributors looking to test the front end with their backend code changes.
  - This option makes the most sense. We provide an empty, dev database instance where developers who _need_ access to the full stack of TalkToBeavs have the ability to test their changes in an isolated environment, away from our users. I see docker being a great option here.
- Open Source, Closed Commit
  - This may not make sense at first, but this option is if we decide that we want tight control over who can access the developer environment of TalkToBeavs. We keep the repo, yet do not allow developers to make changes outside of the founders. This in my opinion defeats the purpose of GitHub, having a MIT license, and creating this in the first place.

I say we stick with option two. If you think the documentation could be better, I think that'd be better served for confluence,   jira, or similar tools. Or by just having `CONTRIBUTING.md` in both the `/backend` and `/frontend` directories to onboard prospective contributors.
